# Generated by Django 2.0.5 on 2018-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsapp', '0002_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='atob',
            field=models.BooleanField(default=True),
        ),
    ]
